package rs.ac.bg.fon.ai.client_mvn.form;

import java.util.logging.Level;
import java.util.logging.Logger;
import rs.ac.bg.fon.ai.client_mvn.controller.KontrolerKIKorisnik;

/**
 *
 * @author Sonja
 */
public class FrmMain extends OpstaEkranskaForma {

    KontrolerKIKorisnik kkik;

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        setTitle("Upravljanje radom pozorišta");
        setLocationRelativeTo(null);
        // setSize(600, 400);
        kkik = new KontrolerKIKorisnik(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOdjavi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblKorisnik = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmGlumac = new javax.swing.JMenu();
        jmPredstava = new javax.swing.JMenu();
        jmRepertoar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOdjavi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnOdjavi.setText("Odjavi se");
        btnOdjavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjaviActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel1.setText("Dobro došli u aplikaciju");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel3.setText("za praćenje rada pozorišta!");

        lblKorisnik.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKorisnik.setText("jLabel4");

        jmGlumac.setText("Glumac");
        jmGlumac.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jmGlumac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmGlumacMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmGlumac);

        jmPredstava.setText("Predstava");
        jmPredstava.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jmPredstava.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmPredstavaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmPredstava);

        jmRepertoar.setText("Repertoar");
        jmRepertoar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jmRepertoar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmRepertoarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmRepertoar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOdjavi)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOdjavi)
                    .addComponent(lblKorisnik))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOdjaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjaviActionPerformed
        try {
            kkik.SOOdjavi();
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOdjaviActionPerformed

    private void jmGlumacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmGlumacMouseClicked
        new FrmGlumci().setVisible(true);
    }//GEN-LAST:event_jmGlumacMouseClicked

    private void jmPredstavaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmPredstavaMouseClicked
        new FrmPredstave().setVisible(true);
    }//GEN-LAST:event_jmPredstavaMouseClicked

    private void jmRepertoarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmRepertoarMouseClicked
        new FrmNoviRepertoar().setVisible(true);
    }//GEN-LAST:event_jmRepertoarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdjavi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmGlumac;
    private javax.swing.JMenu jmPredstava;
    private javax.swing.JMenu jmRepertoar;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblKorisnik;
    // End of variables declaration//GEN-END:variables

    public void setLblKorisnik(String korisnik) {
        lblKorisnik.setText(korisnik);
    }

}
